### ISSUE TITLE
Variable already defined in line 8, "var" can be removed

### ISSUE THREAD

**Issue by Av3r3tt** [hiulit/Delaunator-GDScript#1]
https://github.com/hiulit/Delaunator-GDScript/blob/d7dd218c69c005f026f0fe02f934730ec5a88acc/Delaunator.gd#L144

could instead just be

`hull = []`

Thank you! This is excellent work!

**Comment by hiulit** [comment]
Thanks! I'll check it.

**Comment by hiulit** [comment]
Done! Thanks!
