### ISSUE TITLE
Suggestion: Use static typing

### ISSUE THREAD

**Issue by t-karcher** [hiulit/Delaunator-GDScript#2]
Great script - thanks!

I noticed that you only mentioned the variable types as comment instead of using static typing:

https://github.com/hiulit/Delaunator-GDScript/blob/d7dd218c69c005f026f0fe02f934730ec5a88acc/Delaunator.gd#L6-L7

I wonder whether you could increase the script performance by switching to static typing?

    var coords : PoolRealArray = []
    ...

Even if the performance would not be affected, it would increase readability and has some other advantages, too.

**Comment by hiulit** [comment]
Hey, thanks for the feedback! I can't remember exactly why I left it out, but I think that some typed arrays weren't working correctly. I'll have a look again and see if I can add the types :)

**Comment by hiulit** [comment]
Done, thanks to a this pull request https://github.com/hiulit/Delaunator-GDScript/pull/3
